language: swift
os: osx
osx_image: xcode11
xcode_project: QuizApp/QuizApp.xcodeproj # path to your xcodeproj folder
xcode_scheme: QuizAppTests
script:
- xcodebuild clean build -project QuizApp/QuizApp.xcodeproj CODE_SIGNING_ALLOWED=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
